//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System451.Communication.Dashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System451.Communication.Dashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] _32feetWidcommx64 {
            get {
                object obj = ResourceManager.GetObject("_32feetWidcommx64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _32feetWidcommx86 {
            get {
                object obj = ResourceManager.GetObject("_32feetWidcommx86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap brz {
            get {
                object obj = ResourceManager.GetObject("brz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] InTheHand_Net_Personal {
            get {
                object obj = ResourceManager.GetObject("InTheHand_Net_Personal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] libvlc {
            get {
                object obj = ResourceManager.GetObject("libvlc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] libvlccore {
            get {
                object obj = ResourceManager.GetObject("libvlccore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:ZomB=&quot;clr-namespace:System451.Communication.Dashboard.WPF.Controls;assembly=ZomB&quot; Width=&quot;250&quot; Height=&quot;150&quot;&gt;
        ///	&lt;Grid.ColumnDefinitions&gt;
        ///		&lt;ColumnDefinition Width=&quot;*&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;5&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;*&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;5&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;*&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;5&quot; /&gt;
        ///		&lt;ColumnDefinition Width=&quot;*&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PIDCompositeMarkup {
            get {
                return ResourceManager.GetString("PIDCompositeMarkup", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap TacoFull_small21 {
            get {
                object obj = ResourceManager.GetObject("TacoFull_small21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TacoShell {
            get {
                object obj = ResourceManager.GetObject("TacoShell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] Vlc_DotNet_Core {
            get {
                object obj = ResourceManager.GetObject("Vlc_DotNet_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Vlc_DotNet_Forms {
            get {
                object obj = ResourceManager.GetObject("Vlc_DotNet_Forms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZomB_text {
            get {
                object obj = ResourceManager.GetObject("ZomB_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZomBWFrame {
            get {
                object obj = ResourceManager.GetObject("ZomBWFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZomBZ {
            get {
                object obj = ResourceManager.GetObject("ZomBZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
